CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS check_ins (
  id UUID PRIMARY KEY NOT NULL DEFAULT GEN_RANDOM_UUID(),
  created_at DATE NOT NULL DEFAULT CURRENT_DATE,
  sex TEXT NULL,
  age_range TEXT NULL,
  locality TEXT NULL
);